/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vistar;

import Vistar.Tablas.ModeloTablaLaberinto;
import java.awt.Color;
import java_unidad3.Laberintocontroller;

/**
 *
 * @author franz
 */
public class Laberinto extends javax.swing.JDialog {
    private Laberintocontroller cont = new Laberintocontroller();
    /**
     * Creates new form Laberinto
     *
     * @param parent
     * @param modal
     */
    public Laberinto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        numeroCombo();
        Laberinto.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
    }

    public void generalLaberinto() {
        int filas = Integer.parseInt((String) cbxfilas.getSelectedItem());
        int columnas = Integer.parseInt((String) cdxcolum.getSelectedItem());
        cont.setlaberinto(filas, columnas);
        cont.generalLaberinto();
        actualizarTabla();
    }

    public void numeroCombo() {
        cbxfilas.removeAllItems();
        cdxcolum.removeAllItems();
        for (int i = 10; i <= 100; i++) {
            cbxfilas.addItem(String.valueOf(i));
            cdxcolum.addItem(String.valueOf(i));
        }
    }

    public void actualizarTabla() {
        ModeloTablaLaberinto lab = new ModeloTablaLaberinto();
        lab.setLaberinto(cont.getLaberinto());
        Laberinto.setModel(lab);
        //tamaño de las celdas
        for(int i = 0; i < Laberinto.getColumnCount();i++){
            Laberinto.getColumnModel().getColumn(i).setPreferredWidth(30);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Laberinto = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        cbxfilas = new javax.swing.JComboBox<>();
        cdxcolum = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Laberinto");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        Laberinto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Laberinto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Laberinto.setToolTipText("");
        Laberinto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(Laberinto);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 420, 250);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 60, 420, 260);

        jButton2.setText("General");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(290, 10, 75, 25);

        cbxfilas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxfilas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxfilasActionPerformed(evt);
            }
        });
        jPanel1.add(cbxfilas);
        cbxfilas.setBounds(50, 10, 56, 24);

        cdxcolum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cdxcolum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdxcolumActionPerformed(evt);
            }
        });
        jPanel1.add(cdxcolum);
        cdxcolum.setBounds(200, 10, 56, 24);

        jLabel4.setText("Filas:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 10, 30, 20);

        jLabel2.setText("Columnas:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 10, 60, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 420, 330);

        setSize(new java.awt.Dimension(435, 361));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        generalLaberinto();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbxfilasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxfilasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbxfilasActionPerformed

    private void cdxcolumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdxcolumActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cdxcolumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Laberinto dialog = new Laberinto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Laberinto;
    private javax.swing.JComboBox<String> cbxfilas;
    private javax.swing.JComboBox<String> cdxcolum;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
