/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vistar;

import Vistar.Tablas.ModeloTablaMatriz;
import java_unidad3.Matrizcontrolador;
import javax.swing.JOptionPane;

/**
 *
 * @author franz
 */
public class Matriz extends javax.swing.JDialog {
    private Matrizcontrolador ma = new Matrizcontrolador();

    /**
     * Creates new form Matriz
     *
     * @param parent
     * @param modal
     */
    public Matriz(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Filascolumna();
        mdltabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
    }
    
    public void general() {
        int filas = Integer.parseInt((String) cbxfilas.getSelectedItem());
        int columna = Integer.parseInt((String) cdxcolum.getSelectedItem());
        ma.General(filas, columna);
        ma.generalmatriz();
        subirtablas();
    }

    public void retirarNUM() {
        if (ma.getGeneral() == null) {
            JOptionPane.showMessageDialog(null, "Genere la matriz primero", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int numero = Integer.parseInt((String) cbxnumero.getSelectedItem());
            ma.eliminarNUM(numero);
            subirtablas();
        }
    }

    public void Retirarprimo() {
        ma.eliminarprimo();
        subirtablas();
    }

    public void Filascolumna() {
        cbxfilas.removeAllItems();
        cdxcolum.removeAllItems();
        for (int i = 1; i <= 30; i++) {
            cbxfilas.addItem(String.valueOf(i));
            cdxcolum.addItem(String.valueOf(i));
        }
        cbxnumero.removeAllItems();
        for (int i = 0; i <= 30; i++) {
            cbxnumero.addItem(String.valueOf(i));
        }
    }

    public void subirtablas() {
        ModeloTablaMatriz nuevoModelo = new ModeloTablaMatriz();
        nuevoModelo.setMatriz(ma.getGeneral());
        mdltabla.setModel(nuevoModelo);
    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mdltabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        cbxfilas = new javax.swing.JComboBox<>();
        cdxcolum = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        cbxnumero = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        mdltabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(mdltabla);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 380, 130);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 50, 380, 230);

        jButton1.setText("Retirar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 310, 90, 25);

        jButton2.setText("Quitar numeros primos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 350, 150, 25);

        jLabel2.setText("Columnas:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 10, 60, 20);

        jButton3.setText("General");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(310, 10, 75, 25);

        cbxfilas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxfilas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxfilasActionPerformed(evt);
            }
        });
        getContentPane().add(cbxfilas);
        cbxfilas.setBounds(55, 10, 56, 24);

        cdxcolum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cdxcolum);
        cdxcolum.setBounds(200, 10, 56, 24);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        cbxnumero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbxnumero);
        cbxnumero.setBounds(10, 10, 70, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 340, 90, 50);

        jLabel3.setText("Escoja el numero que desea retirar");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 310, 190, 20);

        jLabel4.setText("Filas:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 10, 30, 20);

        setSize(new java.awt.Dimension(414, 456));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        retirarNUM();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        general();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Retirarprimo();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbxfilasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxfilasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxfilasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Matriz dialog = new Matriz(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxfilas;
    private javax.swing.JComboBox<String> cbxnumero;
    private javax.swing.JComboBox<String> cdxcolum;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTable mdltabla;
    // End of variables declaration//GEN-END:variables
}
