/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package casas.views;

import casas.controller.CasasArchivo;
import casas.modelos.ModelotablaCasas;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class CasasView extends javax.swing.JDialog {

    /**
     * Creates new form CasasView
     */
    public CasasView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        limpiarCampos();
    }

    ModelotablaCasas mta = new ModelotablaCasas();
    CasasArchivo ca = new CasasArchivo();

    private void cargarTabla() {
        mta.setData(ca.listar());
        tblCasas.setModel(mta);
        tblCasas.updateUI();
    }

    private void btnAgregarCasa() {
        try {
            float largo = Float.parseFloat(txtLargo.getText());
            float ancho = Float.parseFloat(txtAncho.getText());
            float altura = Float.parseFloat(txtAltura.getText());
            int nroPisos = Integer.parseInt(txtNroPisos.getText());

            if (ca.guardarCasa(largo, ancho, altura, nroPisos)) {
                JOptionPane.showMessageDialog(null, "Casa guardada exitosamente.", "Guardado", JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese valores numéricos válidos.", "Error", JOptionPane.ERROR_MESSAGE);
                limpiarCampos();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese datos numéricos", "Error", JOptionPane.ERROR_MESSAGE);
            limpiarCampos();
        }
    }

    private void btnVerificarHomonimas() throws IOException {
        String[][] casas = ca.listarCasas("Casas.dat");
        String resultado = ca.verificarHomonimas(casas);
        JOptionPane.showMessageDialog(null, resultado, "Casas Homónimas", JOptionPane.INFORMATION_MESSAGE);
    }

    private void limpiarCampos() {
        txtLargo.setText("");
        txtAncho.setText("");
        txtAltura.setText("");
        txtNroPisos.setText("");
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtNroPisos = new javax.swing.JTextField();
        txtLargo = new javax.swing.JTextField();
        txtAncho = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAgregarCasa = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnVerificarHomonimas = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCasas = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(null);
        getContentPane().add(txtNroPisos);
        txtNroPisos.setBounds(300, 70, 75, 26);
        getContentPane().add(txtLargo);
        txtLargo.setBounds(30, 70, 75, 26);
        getContentPane().add(txtAncho);
        txtAncho.setBounds(120, 70, 75, 26);
        getContentPane().add(txtAltura);
        txtAltura.setBounds(210, 70, 75, 26);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nro Pisos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 50, 80, 16);

        jLabel2.setText("Casas Agregadas:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 170, 100, 16);

        jLabel3.setText("Largo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 50, 30, 16);

        jLabel4.setText("Ancho");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 50, 40, 16);

        jLabel5.setText("Altura");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 50, 40, 16);

        btnAgregarCasa.setText("Agregar Casa");
        btnAgregarCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCasaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarCasa);
        btnAgregarCasa.setBounds(150, 110, 110, 40);

        jLabel6.setText("Ingrese las dimensiones de la casa y el número de pisos:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 20, 350, 16);

        btnVerificarHomonimas.setText("Verificar Homónimas");
        btnVerificarHomonimas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarHomonimasActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerificarHomonimas);
        btnVerificarHomonimas.setBounds(130, 410, 150, 40);

        tblCasas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblCasas);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 190, 360, 210);

        setSize(new java.awt.Dimension(414, 507));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCasaActionPerformed
        btnAgregarCasa();
    }//GEN-LAST:event_btnAgregarCasaActionPerformed

    private void btnVerificarHomonimasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarHomonimasActionPerformed
        try {
            btnVerificarHomonimas();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnVerificarHomonimasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CasasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CasasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CasasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CasasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CasasView dialog = new CasasView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCasa;
    private javax.swing.JButton btnVerificarHomonimas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblCasas;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtAncho;
    private javax.swing.JTextField txtLargo;
    private javax.swing.JTextField txtNroPisos;
    // End of variables declaration//GEN-END:variables
}
